# Generated by Django 2.0.1 on 2018-02-02 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subject',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='subject',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='subject',
            new_name='course',
        ),
    ]
