# Generated by Django 2.0.1 on 2018-02-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20180202_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.AddField(
            model_name='course',
            name='main_language',
            field=models.CharField(default='Java', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='deduction',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
