# Generated by Django 2.0.1 on 2018-03-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20180328_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='color',
            field=models.CharField(default='black', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_src_file',
            field=models.CharField(default='Test.java', max_length=50),
            preserve_default=False,
        ),
    ]
