# Generated by Django 2.0.1 on 2018-04-20 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20180330_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueException',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_exceptions', to='admin.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_exceptions', to='admin.Student')),
            ],
        ),
    ]
